segment readable
table:
db "<zero/><zero/><zero/><zero/><zero/><zero/><zero/><zero/>", 0 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><zero/><zero/>", 1 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><zero/><zero/>", 1 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><zero/><zero/>", 2 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><zero/><zero/>", 1 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><zero/><zero/>", 2 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><zero/><zero/>", 2 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><zero/><zero/>", 3 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><zero/><zero/>", 1 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><zero/><zero/>", 2 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><zero/><zero/>", 2 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><zero/><zero/>", 3 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><zero/><zero/>", 2 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><zero/><zero/>", 3 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><zero/><zero/>", 3 dup 0
db "<one/><one/><one/><one/><zero/><zero/><zero/><zero/>", 4 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><zero/><zero/>", 1 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><zero/><zero/>", 2 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><zero/><zero/>", 2 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><zero/><zero/>", 3 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><zero/><zero/>", 2 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><zero/><zero/>", 3 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><zero/><zero/>", 3 dup 0
db "<one/><one/><one/><zero/><one/><zero/><zero/><zero/>", 4 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><zero/><zero/>", 2 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><zero/><zero/>", 3 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><zero/><zero/>", 3 dup 0
db "<one/><one/><zero/><one/><one/><zero/><zero/><zero/>", 4 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><zero/><zero/>", 3 dup 0
db "<one/><zero/><one/><one/><one/><zero/><zero/><zero/>", 4 dup 0
db "<zero/><one/><one/><one/><one/><zero/><zero/><zero/>", 4 dup 0
db "<one/><one/><one/><one/><one/><zero/><zero/><zero/>", 5 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><zero/><zero/>", 1 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><zero/><zero/>", 2 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><zero/><zero/>", 2 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><zero/><zero/>", 3 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><zero/><zero/>", 2 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><zero/><zero/>", 3 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><zero/><zero/>", 3 dup 0
db "<one/><one/><one/><zero/><zero/><one/><zero/><zero/>", 4 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><zero/><zero/>", 2 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><zero/><zero/>", 3 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><zero/><zero/>", 3 dup 0
db "<one/><one/><zero/><one/><zero/><one/><zero/><zero/>", 4 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><zero/><zero/>", 3 dup 0
db "<one/><zero/><one/><one/><zero/><one/><zero/><zero/>", 4 dup 0
db "<zero/><one/><one/><one/><zero/><one/><zero/><zero/>", 4 dup 0
db "<one/><one/><one/><one/><zero/><one/><zero/><zero/>", 5 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><zero/><zero/>", 2 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><zero/><zero/>", 3 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><zero/><zero/>", 3 dup 0
db "<one/><one/><zero/><zero/><one/><one/><zero/><zero/>", 4 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><zero/><zero/>", 3 dup 0
db "<one/><zero/><one/><zero/><one/><one/><zero/><zero/>", 4 dup 0
db "<zero/><one/><one/><zero/><one/><one/><zero/><zero/>", 4 dup 0
db "<one/><one/><one/><zero/><one/><one/><zero/><zero/>", 5 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><zero/><zero/>", 3 dup 0
db "<one/><zero/><zero/><one/><one/><one/><zero/><zero/>", 4 dup 0
db "<zero/><one/><zero/><one/><one/><one/><zero/><zero/>", 4 dup 0
db "<one/><one/><zero/><one/><one/><one/><zero/><zero/>", 5 dup 0
db "<zero/><zero/><one/><one/><one/><one/><zero/><zero/>", 4 dup 0
db "<one/><zero/><one/><one/><one/><one/><zero/><zero/>", 5 dup 0
db "<zero/><one/><one/><one/><one/><one/><zero/><zero/>", 5 dup 0
db "<one/><one/><one/><one/><one/><one/><zero/><zero/>", 6 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><one/><zero/>", 1 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><one/><zero/>", 2 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><one/><zero/>", 2 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><one/><zero/>", 3 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><one/><zero/>", 2 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><one/><zero/>", 3 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><one/><zero/>", 3 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><one/><zero/>", 4 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><one/><zero/>", 2 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><one/><zero/>", 3 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><one/><zero/>", 3 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><one/><zero/>", 4 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><one/><zero/>", 3 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><one/><zero/>", 4 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><one/><zero/>", 4 dup 0
db "<one/><one/><one/><one/><zero/><zero/><one/><zero/>", 5 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><one/><zero/>", 2 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><one/><zero/>", 3 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><one/><zero/>", 3 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><one/><zero/>", 4 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><one/><zero/>", 3 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><one/><zero/>", 4 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><one/><zero/>", 4 dup 0
db "<one/><one/><one/><zero/><one/><zero/><one/><zero/>", 5 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><one/><zero/>", 3 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><one/><zero/>", 4 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><one/><zero/>", 4 dup 0
db "<one/><one/><zero/><one/><one/><zero/><one/><zero/>", 5 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><one/><zero/>", 4 dup 0
db "<one/><zero/><one/><one/><one/><zero/><one/><zero/>", 5 dup 0
db "<zero/><one/><one/><one/><one/><zero/><one/><zero/>", 5 dup 0
db "<one/><one/><one/><one/><one/><zero/><one/><zero/>", 6 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><one/><zero/>", 2 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><one/><zero/>", 3 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><one/><zero/>", 3 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><one/><zero/>", 4 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><one/><zero/>", 3 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><one/><zero/>", 4 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><one/><zero/>", 4 dup 0
db "<one/><one/><one/><zero/><zero/><one/><one/><zero/>", 5 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><one/><zero/>", 3 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><one/><zero/>", 4 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><one/><zero/>", 4 dup 0
db "<one/><one/><zero/><one/><zero/><one/><one/><zero/>", 5 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><one/><zero/>", 4 dup 0
db "<one/><zero/><one/><one/><zero/><one/><one/><zero/>", 5 dup 0
db "<zero/><one/><one/><one/><zero/><one/><one/><zero/>", 5 dup 0
db "<one/><one/><one/><one/><zero/><one/><one/><zero/>", 6 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><one/><zero/>", 3 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><one/><zero/>", 4 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><one/><zero/>", 4 dup 0
db "<one/><one/><zero/><zero/><one/><one/><one/><zero/>", 5 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><one/><zero/>", 4 dup 0
db "<one/><zero/><one/><zero/><one/><one/><one/><zero/>", 5 dup 0
db "<zero/><one/><one/><zero/><one/><one/><one/><zero/>", 5 dup 0
db "<one/><one/><one/><zero/><one/><one/><one/><zero/>", 6 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><one/><zero/>", 4 dup 0
db "<one/><zero/><zero/><one/><one/><one/><one/><zero/>", 5 dup 0
db "<zero/><one/><zero/><one/><one/><one/><one/><zero/>", 5 dup 0
db "<one/><one/><zero/><one/><one/><one/><one/><zero/>", 6 dup 0
db "<zero/><zero/><one/><one/><one/><one/><one/><zero/>", 5 dup 0
db "<one/><zero/><one/><one/><one/><one/><one/><zero/>", 6 dup 0
db "<zero/><one/><one/><one/><one/><one/><one/><zero/>", 6 dup 0
db "<one/><one/><one/><one/><one/><one/><one/><zero/>", 7 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><zero/><one/>", 1 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><zero/><one/>", 2 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><zero/><one/>", 2 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><zero/><one/>", 3 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><zero/><one/>", 2 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><zero/><one/>", 3 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><zero/><one/>", 3 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><zero/><one/>", 4 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><zero/><one/>", 2 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><zero/><one/>", 3 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><zero/><one/>", 3 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><zero/><one/>", 4 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><zero/><one/>", 3 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><zero/><one/>", 4 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><zero/><one/>", 4 dup 0
db "<one/><one/><one/><one/><zero/><zero/><zero/><one/>", 5 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><zero/><one/>", 2 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><zero/><one/>", 3 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><zero/><one/>", 3 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><zero/><one/>", 4 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><zero/><one/>", 3 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><zero/><one/>", 4 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><zero/><one/>", 4 dup 0
db "<one/><one/><one/><zero/><one/><zero/><zero/><one/>", 5 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><zero/><one/>", 3 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><zero/><one/>", 4 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><zero/><one/>", 4 dup 0
db "<one/><one/><zero/><one/><one/><zero/><zero/><one/>", 5 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><zero/><one/>", 4 dup 0
db "<one/><zero/><one/><one/><one/><zero/><zero/><one/>", 5 dup 0
db "<zero/><one/><one/><one/><one/><zero/><zero/><one/>", 5 dup 0
db "<one/><one/><one/><one/><one/><zero/><zero/><one/>", 6 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><zero/><one/>", 2 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><zero/><one/>", 3 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><zero/><one/>", 3 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><zero/><one/>", 4 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><zero/><one/>", 3 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><zero/><one/>", 4 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><zero/><one/>", 4 dup 0
db "<one/><one/><one/><zero/><zero/><one/><zero/><one/>", 5 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><zero/><one/>", 3 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><zero/><one/>", 4 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><zero/><one/>", 4 dup 0
db "<one/><one/><zero/><one/><zero/><one/><zero/><one/>", 5 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><zero/><one/>", 4 dup 0
db "<one/><zero/><one/><one/><zero/><one/><zero/><one/>", 5 dup 0
db "<zero/><one/><one/><one/><zero/><one/><zero/><one/>", 5 dup 0
db "<one/><one/><one/><one/><zero/><one/><zero/><one/>", 6 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><zero/><one/>", 3 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><zero/><one/>", 4 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><zero/><one/>", 4 dup 0
db "<one/><one/><zero/><zero/><one/><one/><zero/><one/>", 5 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><zero/><one/>", 4 dup 0
db "<one/><zero/><one/><zero/><one/><one/><zero/><one/>", 5 dup 0
db "<zero/><one/><one/><zero/><one/><one/><zero/><one/>", 5 dup 0
db "<one/><one/><one/><zero/><one/><one/><zero/><one/>", 6 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><zero/><one/>", 4 dup 0
db "<one/><zero/><zero/><one/><one/><one/><zero/><one/>", 5 dup 0
db "<zero/><one/><zero/><one/><one/><one/><zero/><one/>", 5 dup 0
db "<one/><one/><zero/><one/><one/><one/><zero/><one/>", 6 dup 0
db "<zero/><zero/><one/><one/><one/><one/><zero/><one/>", 5 dup 0
db "<one/><zero/><one/><one/><one/><one/><zero/><one/>", 6 dup 0
db "<zero/><one/><one/><one/><one/><one/><zero/><one/>", 6 dup 0
db "<one/><one/><one/><one/><one/><one/><zero/><one/>", 7 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><one/><one/>", 2 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><one/><one/>", 3 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><one/><one/>", 3 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><one/><one/>", 4 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><one/><one/>", 3 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><one/><one/>", 4 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><one/><one/>", 4 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><one/><one/>", 5 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><one/><one/>", 3 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><one/><one/>", 4 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><one/><one/>", 4 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><one/><one/>", 5 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><one/><one/>", 4 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><one/><one/>", 5 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><one/><one/>", 5 dup 0
db "<one/><one/><one/><one/><zero/><zero/><one/><one/>", 6 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><one/><one/>", 3 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><one/><one/>", 4 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><one/><one/>", 4 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><one/><one/>", 5 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><one/><one/>", 4 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><one/><one/>", 5 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><one/><one/>", 5 dup 0
db "<one/><one/><one/><zero/><one/><zero/><one/><one/>", 6 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><one/><one/>", 4 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><one/><one/>", 5 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><one/><one/>", 5 dup 0
db "<one/><one/><zero/><one/><one/><zero/><one/><one/>", 6 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><one/><one/>", 5 dup 0
db "<one/><zero/><one/><one/><one/><zero/><one/><one/>", 6 dup 0
db "<zero/><one/><one/><one/><one/><zero/><one/><one/>", 6 dup 0
db "<one/><one/><one/><one/><one/><zero/><one/><one/>", 7 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><one/><one/>", 3 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><one/><one/>", 4 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><one/><one/>", 4 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><one/><one/>", 5 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><one/><one/>", 4 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><one/><one/>", 5 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><one/><one/>", 5 dup 0
db "<one/><one/><one/><zero/><zero/><one/><one/><one/>", 6 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><one/><one/>", 4 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><one/><one/>", 5 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><one/><one/>", 5 dup 0
db "<one/><one/><zero/><one/><zero/><one/><one/><one/>", 6 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><one/><one/>", 5 dup 0
db "<one/><zero/><one/><one/><zero/><one/><one/><one/>", 6 dup 0
db "<zero/><one/><one/><one/><zero/><one/><one/><one/>", 6 dup 0
db "<one/><one/><one/><one/><zero/><one/><one/><one/>", 7 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><one/><one/>", 4 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><one/><one/>", 5 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><one/><one/>", 5 dup 0
db "<one/><one/><zero/><zero/><one/><one/><one/><one/>", 6 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><one/><one/>", 5 dup 0
db "<one/><zero/><one/><zero/><one/><one/><one/><one/>", 6 dup 0
db "<zero/><one/><one/><zero/><one/><one/><one/><one/>", 6 dup 0
db "<one/><one/><one/><zero/><one/><one/><one/><one/>", 7 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><one/><one/>", 5 dup 0
db "<one/><zero/><zero/><one/><one/><one/><one/><one/>", 6 dup 0
db "<zero/><one/><zero/><one/><one/><one/><one/><one/>", 6 dup 0
db "<one/><one/><zero/><one/><one/><one/><one/><one/>", 7 dup 0
db "<zero/><zero/><one/><one/><one/><one/><one/><one/>", 6 dup 0
db "<one/><zero/><one/><one/><one/><one/><one/><one/>", 7 dup 0
db "<zero/><one/><one/><one/><one/><one/><one/><one/>", 7 dup 0
db "<one/><one/><one/><one/><one/><one/><one/><one/>", 8 dup 0
