segment readable
align 64
table:
db "<zero/><zero/><zero/><zero/><zero/><zero/><zero/><zero/>", 8 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<one/><one/><one/><one/><zero/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><zero/><zero/>", 9 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><zero/><zero/>", 10 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><zero/><zero/>", 10 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><zero/><zero/>", 11 dup 0
db "<one/><one/><one/><zero/><one/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><zero/><zero/>", 10 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><zero/><zero/>", 11 dup 0
db "<one/><one/><zero/><one/><one/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><zero/><zero/>", 11 dup 0
db "<one/><zero/><one/><one/><one/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><one/><one/><one/><one/><zero/><zero/><zero/>", 12 dup 0
db "<one/><one/><one/><one/><one/><zero/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><zero/><zero/>", 9 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><zero/><zero/>", 10 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><zero/><zero/>", 10 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><zero/><zero/>", 10 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><zero/><zero/>", 11 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><zero/><zero/>", 11 dup 0
db "<one/><one/><one/><zero/><zero/><one/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><zero/><zero/>", 10 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><zero/><zero/>", 11 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><zero/><zero/>", 11 dup 0
db "<one/><one/><zero/><one/><zero/><one/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><zero/><zero/>", 11 dup 0
db "<one/><zero/><one/><one/><zero/><one/><zero/><zero/>", 12 dup 0
db "<zero/><one/><one/><one/><zero/><one/><zero/><zero/>", 12 dup 0
db "<one/><one/><one/><one/><zero/><one/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><zero/><zero/>", 10 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><zero/><zero/>", 11 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><zero/><zero/>", 11 dup 0
db "<one/><one/><zero/><zero/><one/><one/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><zero/><zero/>", 11 dup 0
db "<one/><zero/><one/><zero/><one/><one/><zero/><zero/>", 12 dup 0
db "<zero/><one/><one/><zero/><one/><one/><zero/><zero/>", 12 dup 0
db "<one/><one/><one/><zero/><one/><one/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><zero/><zero/>", 11 dup 0
db "<one/><zero/><zero/><one/><one/><one/><zero/><zero/>", 12 dup 0
db "<zero/><one/><zero/><one/><one/><one/><zero/><zero/>", 12 dup 0
db "<one/><one/><zero/><one/><one/><one/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><one/><one/><one/><one/><zero/><zero/>", 12 dup 0
db "<one/><zero/><one/><one/><one/><one/><zero/><zero/>", 13 dup 0
db "<zero/><one/><one/><one/><one/><one/><zero/><zero/>", 13 dup 0
db "<one/><one/><one/><one/><one/><one/><zero/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><one/><zero/>", 9 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><one/><zero/>", 10 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><one/><zero/>", 10 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><one/><zero/>", 11 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><one/><zero/>", 10 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><one/><zero/>", 11 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><one/><zero/>", 11 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><one/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><one/><zero/>", 10 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><one/><zero/>", 11 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><one/><zero/>", 11 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><one/><zero/>", 12 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><one/><zero/>", 11 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><one/><zero/>", 12 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><one/><zero/>", 12 dup 0
db "<one/><one/><one/><one/><zero/><zero/><one/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><one/><zero/>", 10 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><one/><zero/>", 11 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><one/><zero/>", 11 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><one/><zero/>", 12 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><one/><zero/>", 11 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><one/><zero/>", 12 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><one/><zero/>", 12 dup 0
db "<one/><one/><one/><zero/><one/><zero/><one/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><one/><zero/>", 11 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><one/><zero/>", 12 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><one/><zero/>", 12 dup 0
db "<one/><one/><zero/><one/><one/><zero/><one/><zero/>", 13 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><one/><zero/>", 12 dup 0
db "<one/><zero/><one/><one/><one/><zero/><one/><zero/>", 13 dup 0
db "<zero/><one/><one/><one/><one/><zero/><one/><zero/>", 13 dup 0
db "<one/><one/><one/><one/><one/><zero/><one/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><one/><zero/>", 10 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><one/><zero/>", 11 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><one/><zero/>", 11 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><one/><zero/>", 12 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><one/><zero/>", 11 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><one/><zero/>", 12 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><one/><zero/>", 12 dup 0
db "<one/><one/><one/><zero/><zero/><one/><one/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><one/><zero/>", 11 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><one/><zero/>", 12 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><one/><zero/>", 12 dup 0
db "<one/><one/><zero/><one/><zero/><one/><one/><zero/>", 13 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><one/><zero/>", 12 dup 0
db "<one/><zero/><one/><one/><zero/><one/><one/><zero/>", 13 dup 0
db "<zero/><one/><one/><one/><zero/><one/><one/><zero/>", 13 dup 0
db "<one/><one/><one/><one/><zero/><one/><one/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><one/><zero/>", 11 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><one/><zero/>", 12 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><one/><zero/>", 12 dup 0
db "<one/><one/><zero/><zero/><one/><one/><one/><zero/>", 13 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><one/><zero/>", 12 dup 0
db "<one/><zero/><one/><zero/><one/><one/><one/><zero/>", 13 dup 0
db "<zero/><one/><one/><zero/><one/><one/><one/><zero/>", 13 dup 0
db "<one/><one/><one/><zero/><one/><one/><one/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><one/><zero/>", 12 dup 0
db "<one/><zero/><zero/><one/><one/><one/><one/><zero/>", 13 dup 0
db "<zero/><one/><zero/><one/><one/><one/><one/><zero/>", 13 dup 0
db "<one/><one/><zero/><one/><one/><one/><one/><zero/>", 14 dup 0
db "<zero/><zero/><one/><one/><one/><one/><one/><zero/>", 13 dup 0
db "<one/><zero/><one/><one/><one/><one/><one/><zero/>", 14 dup 0
db "<zero/><one/><one/><one/><one/><one/><one/><zero/>", 14 dup 0
db "<one/><one/><one/><one/><one/><one/><one/><zero/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><zero/><one/>", 9 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><zero/><one/>", 10 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><zero/><one/>", 10 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><zero/><one/>", 11 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><zero/><one/>", 10 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><zero/><one/>", 11 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><zero/><one/>", 11 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><zero/><one/>", 12 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><zero/><one/>", 10 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><zero/><one/>", 11 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><zero/><one/>", 11 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><zero/><one/>", 12 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><zero/><one/>", 11 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><zero/><one/>", 12 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><zero/><one/>", 12 dup 0
db "<one/><one/><one/><one/><zero/><zero/><zero/><one/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><zero/><one/>", 10 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><zero/><one/>", 11 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><zero/><one/>", 11 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><zero/><one/>", 12 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><zero/><one/>", 11 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><zero/><one/>", 12 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><zero/><one/>", 12 dup 0
db "<one/><one/><one/><zero/><one/><zero/><zero/><one/>", 13 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><zero/><one/>", 11 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><zero/><one/>", 12 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><zero/><one/>", 12 dup 0
db "<one/><one/><zero/><one/><one/><zero/><zero/><one/>", 13 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><zero/><one/>", 12 dup 0
db "<one/><zero/><one/><one/><one/><zero/><zero/><one/>", 13 dup 0
db "<zero/><one/><one/><one/><one/><zero/><zero/><one/>", 13 dup 0
db "<one/><one/><one/><one/><one/><zero/><zero/><one/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><zero/><one/>", 10 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><zero/><one/>", 11 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><zero/><one/>", 11 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><zero/><one/>", 12 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><zero/><one/>", 11 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><zero/><one/>", 12 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><zero/><one/>", 12 dup 0
db "<one/><one/><one/><zero/><zero/><one/><zero/><one/>", 13 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><zero/><one/>", 11 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><zero/><one/>", 12 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><zero/><one/>", 12 dup 0
db "<one/><one/><zero/><one/><zero/><one/><zero/><one/>", 13 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><zero/><one/>", 12 dup 0
db "<one/><zero/><one/><one/><zero/><one/><zero/><one/>", 13 dup 0
db "<zero/><one/><one/><one/><zero/><one/><zero/><one/>", 13 dup 0
db "<one/><one/><one/><one/><zero/><one/><zero/><one/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><zero/><one/>", 11 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><zero/><one/>", 12 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><zero/><one/>", 12 dup 0
db "<one/><one/><zero/><zero/><one/><one/><zero/><one/>", 13 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><zero/><one/>", 12 dup 0
db "<one/><zero/><one/><zero/><one/><one/><zero/><one/>", 13 dup 0
db "<zero/><one/><one/><zero/><one/><one/><zero/><one/>", 13 dup 0
db "<one/><one/><one/><zero/><one/><one/><zero/><one/>", 14 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><zero/><one/>", 12 dup 0
db "<one/><zero/><zero/><one/><one/><one/><zero/><one/>", 13 dup 0
db "<zero/><one/><zero/><one/><one/><one/><zero/><one/>", 13 dup 0
db "<one/><one/><zero/><one/><one/><one/><zero/><one/>", 14 dup 0
db "<zero/><zero/><one/><one/><one/><one/><zero/><one/>", 13 dup 0
db "<one/><zero/><one/><one/><one/><one/><zero/><one/>", 14 dup 0
db "<zero/><one/><one/><one/><one/><one/><zero/><one/>", 14 dup 0
db "<one/><one/><one/><one/><one/><one/><zero/><one/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><one/><one/>", 10 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><one/><one/>", 11 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><one/><one/>", 11 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><one/><one/>", 12 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><one/><one/>", 11 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><one/><one/>", 12 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><one/><one/>", 12 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><one/><one/>", 13 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><one/><one/>", 11 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><one/><one/>", 12 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><one/><one/>", 12 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><one/><one/>", 13 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><one/><one/>", 12 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><one/><one/>", 13 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><one/><one/>", 13 dup 0
db "<one/><one/><one/><one/><zero/><zero/><one/><one/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><one/><one/>", 11 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><one/><one/>", 12 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><one/><one/>", 12 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><one/><one/>", 13 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><one/><one/>", 12 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><one/><one/>", 13 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><one/><one/>", 13 dup 0
db "<one/><one/><one/><zero/><one/><zero/><one/><one/>", 14 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><one/><one/>", 12 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><one/><one/>", 13 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><one/><one/>", 13 dup 0
db "<one/><one/><zero/><one/><one/><zero/><one/><one/>", 14 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><one/><one/>", 13 dup 0
db "<one/><zero/><one/><one/><one/><zero/><one/><one/>", 14 dup 0
db "<zero/><one/><one/><one/><one/><zero/><one/><one/>", 14 dup 0
db "<one/><one/><one/><one/><one/><zero/><one/><one/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><one/><one/>", 11 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><one/><one/>", 12 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><one/><one/>", 12 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><one/><one/>", 13 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><one/><one/>", 12 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><one/><one/>", 13 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><one/><one/>", 13 dup 0
db "<one/><one/><one/><zero/><zero/><one/><one/><one/>", 14 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><one/><one/>", 12 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><one/><one/>", 13 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><one/><one/>", 13 dup 0
db "<one/><one/><zero/><one/><zero/><one/><one/><one/>", 14 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><one/><one/>", 13 dup 0
db "<one/><zero/><one/><one/><zero/><one/><one/><one/>", 14 dup 0
db "<zero/><one/><one/><one/><zero/><one/><one/><one/>", 14 dup 0
db "<one/><one/><one/><one/><zero/><one/><one/><one/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><one/><one/>", 12 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><one/><one/>", 13 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><one/><one/>", 13 dup 0
db "<one/><one/><zero/><zero/><one/><one/><one/><one/>", 14 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><one/><one/>", 13 dup 0
db "<one/><zero/><one/><zero/><one/><one/><one/><one/>", 14 dup 0
db "<zero/><one/><one/><zero/><one/><one/><one/><one/>", 14 dup 0
db "<one/><one/><one/><zero/><one/><one/><one/><one/>", 15 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><one/><one/>", 13 dup 0
db "<one/><zero/><zero/><one/><one/><one/><one/><one/>", 14 dup 0
db "<zero/><one/><zero/><one/><one/><one/><one/><one/>", 14 dup 0
db "<one/><one/><zero/><one/><one/><one/><one/><one/>", 15 dup 0
db "<zero/><zero/><one/><one/><one/><one/><one/><one/>", 14 dup 0
db "<one/><zero/><one/><one/><one/><one/><one/><one/>", 15 dup 0
db "<zero/><one/><one/><one/><one/><one/><one/><one/>", 15 dup 0
db "<one/><one/><one/><one/><one/><one/><one/><one/>", 16 dup 0
