segment readable

align 64
lengths: dq 56,55,55,54,55,54,54,53,55,54,54,53,54,53,53,52,55,54,54,53,54,53,53,52,54,53,53,52,53,52,52,51,55,54,54,53,54,53,53,52,54,53,53,52,53,52,52,51,54,53,53,52,53,52,52,51,53,52,52,51,52,51,51,50,55,54,54,53,54,53,53,52,54,53,53,52,53,52,52,51,54,53,53,52,53,52,52,51,53,52,52,51,52,51,51,50,54,53,53,52,53,52,52,51,53,52,52,51,52,51,51,50,53,52,52,51,52,51,51,50,52,51,51,50,51,50,50,49,55,54,54,53,54,53,53,52,54,53,53,52,53,52,52,51,54,53,53,52,53,52,52,51,53,52,52,51,52,51,51,50,54,53,53,52,53,52,52,51,53,52,52,51,52,51,51,50,53,52,52,51,52,51,51,50,52,51,51,50,51,50,50,49,54,53,53,52,53,52,52,51,53,52,52,51,52,51,51,50,53,52,52,51,52,51,51,50,52,51,51,50,51,50,50,49,53,52,52,51,52,51,51,50,52,51,51,50,51,50,50,49,52,51,51,50,51,50,50,49,51,50,50,49,50,49,49,48

align 64
table:
db "<zero/><zero/><zero/><zero/><zero/><zero/><zero/><zero/>", 8 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><zero/><zero/>", 9 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><zero/><zero/>", 10 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><zero/><zero/>", 11 dup 0
db "<one/><one/><one/><one/><zero/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><zero/><zero/>", 9 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><zero/><zero/>", 10 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><zero/><zero/>", 10 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><zero/><zero/>", 10 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><zero/><zero/>", 11 dup 0
db "<one/><one/><one/><zero/><one/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><zero/><zero/>", 10 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><zero/><zero/>", 11 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><zero/><zero/>", 11 dup 0
db "<one/><one/><zero/><one/><one/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><zero/><zero/>", 11 dup 0
db "<one/><zero/><one/><one/><one/><zero/><zero/><zero/>", 12 dup 0
db "<zero/><one/><one/><one/><one/><zero/><zero/><zero/>", 12 dup 0
db "<one/><one/><one/><one/><one/><zero/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><zero/><zero/>", 9 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><zero/><zero/>", 10 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><zero/><zero/>", 10 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><zero/><zero/>", 11 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><zero/><zero/>", 10 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><zero/><zero/>", 11 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><zero/><zero/>", 11 dup 0
db "<one/><one/><one/><zero/><zero/><one/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><zero/><zero/>", 10 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><zero/><zero/>", 11 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><zero/><zero/>", 11 dup 0
db "<one/><one/><zero/><one/><zero/><one/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><zero/><zero/>", 11 dup 0
db "<one/><zero/><one/><one/><zero/><one/><zero/><zero/>", 12 dup 0
db "<zero/><one/><one/><one/><zero/><one/><zero/><zero/>", 12 dup 0
db "<one/><one/><one/><one/><zero/><one/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><zero/><zero/>", 10 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><zero/><zero/>", 11 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><zero/><zero/>", 11 dup 0
db "<one/><one/><zero/><zero/><one/><one/><zero/><zero/>", 12 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><zero/><zero/>", 11 dup 0
db "<one/><zero/><one/><zero/><one/><one/><zero/><zero/>", 12 dup 0
db "<zero/><one/><one/><zero/><one/><one/><zero/><zero/>", 12 dup 0
db "<one/><one/><one/><zero/><one/><one/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><zero/><zero/>", 11 dup 0
db "<one/><zero/><zero/><one/><one/><one/><zero/><zero/>", 12 dup 0
db "<zero/><one/><zero/><one/><one/><one/><zero/><zero/>", 12 dup 0
db "<one/><one/><zero/><one/><one/><one/><zero/><zero/>", 13 dup 0
db "<zero/><zero/><one/><one/><one/><one/><zero/><zero/>", 12 dup 0
db "<one/><zero/><one/><one/><one/><one/><zero/><zero/>", 13 dup 0
db "<zero/><one/><one/><one/><one/><one/><zero/><zero/>", 13 dup 0
db "<one/><one/><one/><one/><one/><one/><zero/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><one/><zero/>", 9 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><one/><zero/>", 10 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><one/><zero/>", 10 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><one/><zero/>", 11 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><one/><zero/>", 10 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><one/><zero/>", 11 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><one/><zero/>", 11 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><one/><zero/>", 12 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><one/><zero/>", 10 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><one/><zero/>", 11 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><one/><zero/>", 11 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><one/><zero/>", 12 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><one/><zero/>", 11 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><one/><zero/>", 12 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><one/><zero/>", 12 dup 0
db "<one/><one/><one/><one/><zero/><zero/><one/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><one/><zero/>", 10 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><one/><zero/>", 11 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><one/><zero/>", 11 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><one/><zero/>", 12 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><one/><zero/>", 11 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><one/><zero/>", 12 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><one/><zero/>", 12 dup 0
db "<one/><one/><one/><zero/><one/><zero/><one/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><one/><zero/>", 11 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><one/><zero/>", 12 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><one/><zero/>", 12 dup 0
db "<one/><one/><zero/><one/><one/><zero/><one/><zero/>", 13 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><one/><zero/>", 12 dup 0
db "<one/><zero/><one/><one/><one/><zero/><one/><zero/>", 13 dup 0
db "<zero/><one/><one/><one/><one/><zero/><one/><zero/>", 13 dup 0
db "<one/><one/><one/><one/><one/><zero/><one/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><one/><zero/>", 10 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><one/><zero/>", 11 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><one/><zero/>", 11 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><one/><zero/>", 12 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><one/><zero/>", 11 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><one/><zero/>", 12 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><one/><zero/>", 12 dup 0
db "<one/><one/><one/><zero/><zero/><one/><one/><zero/>", 13 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><one/><zero/>", 11 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><one/><zero/>", 12 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><one/><zero/>", 12 dup 0
db "<one/><one/><zero/><one/><zero/><one/><one/><zero/>", 13 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><one/><zero/>", 12 dup 0
db "<one/><zero/><one/><one/><zero/><one/><one/><zero/>", 13 dup 0
db "<zero/><one/><one/><one/><zero/><one/><one/><zero/>", 13 dup 0
db "<one/><one/><one/><one/><zero/><one/><one/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><one/><zero/>", 11 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><one/><zero/>", 12 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><one/><zero/>", 12 dup 0
db "<one/><one/><zero/><zero/><one/><one/><one/><zero/>", 13 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><one/><zero/>", 12 dup 0
db "<one/><zero/><one/><zero/><one/><one/><one/><zero/>", 13 dup 0
db "<zero/><one/><one/><zero/><one/><one/><one/><zero/>", 13 dup 0
db "<one/><one/><one/><zero/><one/><one/><one/><zero/>", 14 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><one/><zero/>", 12 dup 0
db "<one/><zero/><zero/><one/><one/><one/><one/><zero/>", 13 dup 0
db "<zero/><one/><zero/><one/><one/><one/><one/><zero/>", 13 dup 0
db "<one/><one/><zero/><one/><one/><one/><one/><zero/>", 14 dup 0
db "<zero/><zero/><one/><one/><one/><one/><one/><zero/>", 13 dup 0
db "<one/><zero/><one/><one/><one/><one/><one/><zero/>", 14 dup 0
db "<zero/><one/><one/><one/><one/><one/><one/><zero/>", 14 dup 0
db "<one/><one/><one/><one/><one/><one/><one/><zero/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><zero/><one/>", 9 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><zero/><one/>", 10 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><zero/><one/>", 10 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><zero/><one/>", 11 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><zero/><one/>", 10 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><zero/><one/>", 11 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><zero/><one/>", 11 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><zero/><one/>", 12 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><zero/><one/>", 10 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><zero/><one/>", 11 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><zero/><one/>", 11 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><zero/><one/>", 12 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><zero/><one/>", 11 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><zero/><one/>", 12 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><zero/><one/>", 12 dup 0
db "<one/><one/><one/><one/><zero/><zero/><zero/><one/>", 13 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><zero/><one/>", 10 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><zero/><one/>", 11 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><zero/><one/>", 11 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><zero/><one/>", 12 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><zero/><one/>", 11 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><zero/><one/>", 12 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><zero/><one/>", 12 dup 0
db "<one/><one/><one/><zero/><one/><zero/><zero/><one/>", 13 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><zero/><one/>", 11 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><zero/><one/>", 12 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><zero/><one/>", 12 dup 0
db "<one/><one/><zero/><one/><one/><zero/><zero/><one/>", 13 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><zero/><one/>", 12 dup 0
db "<one/><zero/><one/><one/><one/><zero/><zero/><one/>", 13 dup 0
db "<zero/><one/><one/><one/><one/><zero/><zero/><one/>", 13 dup 0
db "<one/><one/><one/><one/><one/><zero/><zero/><one/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><zero/><one/>", 10 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><zero/><one/>", 11 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><zero/><one/>", 11 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><zero/><one/>", 12 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><zero/><one/>", 11 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><zero/><one/>", 12 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><zero/><one/>", 12 dup 0
db "<one/><one/><one/><zero/><zero/><one/><zero/><one/>", 13 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><zero/><one/>", 11 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><zero/><one/>", 12 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><zero/><one/>", 12 dup 0
db "<one/><one/><zero/><one/><zero/><one/><zero/><one/>", 13 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><zero/><one/>", 12 dup 0
db "<one/><zero/><one/><one/><zero/><one/><zero/><one/>", 13 dup 0
db "<zero/><one/><one/><one/><zero/><one/><zero/><one/>", 13 dup 0
db "<one/><one/><one/><one/><zero/><one/><zero/><one/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><zero/><one/>", 11 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><zero/><one/>", 12 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><zero/><one/>", 12 dup 0
db "<one/><one/><zero/><zero/><one/><one/><zero/><one/>", 13 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><zero/><one/>", 12 dup 0
db "<one/><zero/><one/><zero/><one/><one/><zero/><one/>", 13 dup 0
db "<zero/><one/><one/><zero/><one/><one/><zero/><one/>", 13 dup 0
db "<one/><one/><one/><zero/><one/><one/><zero/><one/>", 14 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><zero/><one/>", 12 dup 0
db "<one/><zero/><zero/><one/><one/><one/><zero/><one/>", 13 dup 0
db "<zero/><one/><zero/><one/><one/><one/><zero/><one/>", 13 dup 0
db "<one/><one/><zero/><one/><one/><one/><zero/><one/>", 14 dup 0
db "<zero/><zero/><one/><one/><one/><one/><zero/><one/>", 13 dup 0
db "<one/><zero/><one/><one/><one/><one/><zero/><one/>", 14 dup 0
db "<zero/><one/><one/><one/><one/><one/><zero/><one/>", 14 dup 0
db "<one/><one/><one/><one/><one/><one/><zero/><one/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><zero/><zero/><one/><one/>", 10 dup 0
db "<one/><zero/><zero/><zero/><zero/><zero/><one/><one/>", 11 dup 0
db "<zero/><one/><zero/><zero/><zero/><zero/><one/><one/>", 11 dup 0
db "<one/><one/><zero/><zero/><zero/><zero/><one/><one/>", 12 dup 0
db "<zero/><zero/><one/><zero/><zero/><zero/><one/><one/>", 11 dup 0
db "<one/><zero/><one/><zero/><zero/><zero/><one/><one/>", 12 dup 0
db "<zero/><one/><one/><zero/><zero/><zero/><one/><one/>", 12 dup 0
db "<one/><one/><one/><zero/><zero/><zero/><one/><one/>", 13 dup 0
db "<zero/><zero/><zero/><one/><zero/><zero/><one/><one/>", 11 dup 0
db "<one/><zero/><zero/><one/><zero/><zero/><one/><one/>", 12 dup 0
db "<zero/><one/><zero/><one/><zero/><zero/><one/><one/>", 12 dup 0
db "<one/><one/><zero/><one/><zero/><zero/><one/><one/>", 13 dup 0
db "<zero/><zero/><one/><one/><zero/><zero/><one/><one/>", 12 dup 0
db "<one/><zero/><one/><one/><zero/><zero/><one/><one/>", 13 dup 0
db "<zero/><one/><one/><one/><zero/><zero/><one/><one/>", 13 dup 0
db "<one/><one/><one/><one/><zero/><zero/><one/><one/>", 14 dup 0
db "<zero/><zero/><zero/><zero/><one/><zero/><one/><one/>", 11 dup 0
db "<one/><zero/><zero/><zero/><one/><zero/><one/><one/>", 12 dup 0
db "<zero/><one/><zero/><zero/><one/><zero/><one/><one/>", 12 dup 0
db "<one/><one/><zero/><zero/><one/><zero/><one/><one/>", 13 dup 0
db "<zero/><zero/><one/><zero/><one/><zero/><one/><one/>", 12 dup 0
db "<one/><zero/><one/><zero/><one/><zero/><one/><one/>", 13 dup 0
db "<zero/><one/><one/><zero/><one/><zero/><one/><one/>", 13 dup 0
db "<one/><one/><one/><zero/><one/><zero/><one/><one/>", 14 dup 0
db "<zero/><zero/><zero/><one/><one/><zero/><one/><one/>", 12 dup 0
db "<one/><zero/><zero/><one/><one/><zero/><one/><one/>", 13 dup 0
db "<zero/><one/><zero/><one/><one/><zero/><one/><one/>", 13 dup 0
db "<one/><one/><zero/><one/><one/><zero/><one/><one/>", 14 dup 0
db "<zero/><zero/><one/><one/><one/><zero/><one/><one/>", 13 dup 0
db "<one/><zero/><one/><one/><one/><zero/><one/><one/>", 14 dup 0
db "<zero/><one/><one/><one/><one/><zero/><one/><one/>", 14 dup 0
db "<one/><one/><one/><one/><one/><zero/><one/><one/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><zero/><one/><one/><one/>", 11 dup 0
db "<one/><zero/><zero/><zero/><zero/><one/><one/><one/>", 12 dup 0
db "<zero/><one/><zero/><zero/><zero/><one/><one/><one/>", 12 dup 0
db "<one/><one/><zero/><zero/><zero/><one/><one/><one/>", 13 dup 0
db "<zero/><zero/><one/><zero/><zero/><one/><one/><one/>", 12 dup 0
db "<one/><zero/><one/><zero/><zero/><one/><one/><one/>", 13 dup 0
db "<zero/><one/><one/><zero/><zero/><one/><one/><one/>", 13 dup 0
db "<one/><one/><one/><zero/><zero/><one/><one/><one/>", 14 dup 0
db "<zero/><zero/><zero/><one/><zero/><one/><one/><one/>", 12 dup 0
db "<one/><zero/><zero/><one/><zero/><one/><one/><one/>", 13 dup 0
db "<zero/><one/><zero/><one/><zero/><one/><one/><one/>", 13 dup 0
db "<one/><one/><zero/><one/><zero/><one/><one/><one/>", 14 dup 0
db "<zero/><zero/><one/><one/><zero/><one/><one/><one/>", 13 dup 0
db "<one/><zero/><one/><one/><zero/><one/><one/><one/>", 14 dup 0
db "<zero/><one/><one/><one/><zero/><one/><one/><one/>", 14 dup 0
db "<one/><one/><one/><one/><zero/><one/><one/><one/>", 15 dup 0
db "<zero/><zero/><zero/><zero/><one/><one/><one/><one/>", 12 dup 0
db "<one/><zero/><zero/><zero/><one/><one/><one/><one/>", 13 dup 0
db "<zero/><one/><zero/><zero/><one/><one/><one/><one/>", 13 dup 0
db "<one/><one/><zero/><zero/><one/><one/><one/><one/>", 14 dup 0
db "<zero/><zero/><one/><zero/><one/><one/><one/><one/>", 13 dup 0
db "<one/><zero/><one/><zero/><one/><one/><one/><one/>", 14 dup 0
db "<zero/><one/><one/><zero/><one/><one/><one/><one/>", 14 dup 0
db "<one/><one/><one/><zero/><one/><one/><one/><one/>", 15 dup 0
db "<zero/><zero/><zero/><one/><one/><one/><one/><one/>", 13 dup 0
db "<one/><zero/><zero/><one/><one/><one/><one/><one/>", 14 dup 0
db "<zero/><one/><zero/><one/><one/><one/><one/><one/>", 14 dup 0
db "<one/><one/><zero/><one/><one/><one/><one/><one/>", 15 dup 0
db "<zero/><zero/><one/><one/><one/><one/><one/><one/>", 14 dup 0
db "<one/><zero/><one/><one/><one/><one/><one/><one/>", 15 dup 0
db "<zero/><one/><one/><one/><one/><one/><one/><one/>", 15 dup 0
db "<one/><one/><one/><one/><one/><one/><one/><one/>", 16 dup 0
